.TH redo-ifcreate 1 "2011-01-18" "Redo 0\.05"
.SH NAME
.PP
redo-ifcreate - rebuild the current target if source files are
created
.SH SYNOPSIS
.PP
redo-ifcreate [sources\.\.\.]
.SH DESCRIPTION
.PP
Normally redo-ifcreate is run from a \.do file that has been
executed by \f[B]redo\f[](1)\. See \f[B]redo\f[](1) for more
details\.
.PP
redo-ifcreate takes a list of nonexistent files (\f[I]sources\f[])
and adds them as dependencies to the current target (the one
calling redo-ifcreate)\. If any of those files are created in the
future, the target will be marked as needing to be rebuilt\.
.PP
If one of the given files exists at the time redo-ifcreate is
called, it will return a nonzero exit code\.
.PP
If you want to declare dependencies on files that already exist,
use \f[B]redo-ifchange\f[](1) instead\.
.SH REDO
.PP
Part of the \f[B]redo\f[](1) suite\.
.SH CREDITS
.PP
The original concept for \f[B]redo\f[] was created by D\. J\.
Bernstein and documented on his web site
(http://cr\.yp\.to/redo\.html)\. This independent implementation
was created by Avery Pennarun and you can find its source code at
http://github\.com/apenwarr/redo\.
.SH SEE ALSO
.PP
\f[B]redo\f[](1), \f[B]redo-ifchange\f[](1),
\f[B]redo-always\f[](1), \f[B]redo-stamp\f[](1)
.SH AUTHOR
Avery Pennarun <apenwarr@gmail.com>
